<?php

declare(strict_types=1);

namespace App\Core;

use PDO;
use PDOException;
use RuntimeException;

final class Database
{
    private static ?PDO $connection = null;

    /**
     * Get the active PDO connection.
     */
    public static function connection(): PDO
    {
        if (self::$connection instanceof PDO) {
            return self::$connection;
        }

        $config = require BASE_PATH . '/config/database.php';

        $driver = $config['driver'];

        if ($driver !== 'mysql') {
            throw new RuntimeException(
                "Unsupported database driver: {$driver}"
            );
        }

        $dsn = sprintf(
            'mysql:host=%s;port=%d;dbname=%s;charset=%s',
            $config['host'],
            $config['port'],
            $config['database'],
            $config['charset']
        );

        try {
            self::$connection = new PDO(
                $dsn,
                $config['username'],
                $config['password'],
                $config['options']
            );
        } catch (PDOException $exception) {
            /*
             * Never expose raw database credentials or internal
             * connection information to users.
             */
            if (
                function_exists('config')
                && config('app.debug', false)
            ) {
                throw new RuntimeException(
                    'Database connection failed: '
                    . $exception->getMessage(),
                    (int) $exception->getCode(),
                    $exception
                );
            }

            throw new RuntimeException(
                'Database connection failed.'
            );
        }

        return self::$connection;
    }

    /**
     * Execute a SELECT-style query.
     *
     * Example:
     *
     * $users = Database::query(
     *     'SELECT * FROM users WHERE role = :role',
     *     ['role' => 'teacher']
     * );
     */
    public static function query(
        string $sql,
        array $parameters = []
    ): \PDOStatement {
        $statement = self::connection()->prepare($sql);

        $statement->execute($parameters);

        return $statement;
    }

    /**
     * Fetch a single row.
     */
    public static function first(
        string $sql,
        array $parameters = []
    ): ?array {
        $statement = self::query(
            $sql,
            $parameters
        );

        $result = $statement->fetch();

        return $result === false
            ? null
            : $result;
    }

    /**
     * Fetch all rows.
     */
    public static function all(
        string $sql,
        array $parameters = []
    ): array {
        $statement = self::query(
            $sql,
            $parameters
        );

        return $statement->fetchAll();
    }

    /**
     * Execute INSERT, UPDATE or DELETE.
     */
    public static function execute(
        string $sql,
        array $parameters = []
    ): int {
        $statement = self::query(
            $sql,
            $parameters
        );

        return $statement->rowCount();
    }

    /**
     * Get the ID generated by the last INSERT.
     */
    public static function lastInsertId(): int
    {
        return (int) self::connection()->lastInsertId();
    }

    /**
     * Start a transaction.
     */
    public static function beginTransaction(): void
    {
        self::connection()->beginTransaction();
    }

    /**
     * Commit the current transaction.
     */
    public static function commit(): void
    {
        self::connection()->commit();
    }

    /**
     * Roll back the current transaction.
     */
    public static function rollBack(): void
    {
        self::connection()->rollBack();
    }

    /**
     * Check whether a transaction is active.
     */
    public static function inTransaction(): bool
    {
        return self::connection()->inTransaction();
    }

    /**
     * Execute a callback inside a transaction.
     *
     * If the callback throws an exception, the transaction
     * is automatically rolled back.
     */
    public static function transaction(
        callable $callback
    ): mixed {
        self::beginTransaction();

        try {
            $result = $callback();

            self::commit();

            return $result;
        } catch (\Throwable $exception) {
            if (self::inTransaction()) {
                self::rollBack();
            }

            throw $exception;
        }
    }
}